apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-admin-install
  labels:
    app.kubernetes.io/name: {{ template "ranger.name" . }}
    chart: {{ template "ranger.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  {{- (.Files.Glob "ranger-admin/*").AsConfig | nindent 2 }}