# Default values for ranger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
extraLabels: {}

server:
  replicaCount: 1
  image:
    # repository: armadik/ranger-admin
    # tag: 2.4.0
    repository: melodydocker/ranger-admin
    tag: latest
    pullPolicy: Always

  # Network configuration
  service:
    type: ClusterIP
    annotations: {}
  
  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  #   initialDelaySeconds: 60
  #   timeoutSeconds: 5
  #   failureThreshold: 6
  #   periodSeconds: 10
  #   successThreshold: 1
  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  #   initialDelaySeconds: 5
  #   periodSeconds: 10
  #   timeoutSeconds: 3  
  #   successThreshold: 1
  #   failureThreshold: 3
  resources: {}
  # requests:
  #   cpu: "100m"
  #   memory: "256Mi"
  # limits:
  #   cpu: "500m"
  #   memory: "512Mi"
  nodeSelector: {}
  podAnnotations: {} 
  annotations: {}

usersync:
  replicaCount: 1
  image:
    # repository: armadik/ranger-usersync
    # tag: 2.4.0
    repository: melodydocker/ranger-usersync
    tag: latest
    pullPolicy: Always

  # Network configuration
  service:
    type: ClusterIP
    annotations: {}
  
  podAnnotations: {} 
  annotations: {}
  nodeSelector: {}
  resources: {}
  # requests:
  #   cpu: "100m"
  #   memory: "256Mi"
  # limits:
  #   cpu: "500m"
  #   memory: "512Mi"

postgres:
  replicaCount: 1
  image:
    repository: postgres
    # tag: 14.12
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      memory: 256Mi
      cpu: 100m

  service:
    type: ClusterIP
    annotations: {}

  livenessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host=$POD_IP
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    exec:
      command:
      - sh
      - -c
      - exec pg_isready --host=$POD_IP
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3  

  env:
    PGDATA: /usr/lib/postgresql/data
    POSTGRES_USER: POSTGRES
    POSTGRES_PASSWORD: POSTGRES
    POSTGRES_HOST_AUTH_METHOD: md5
    POSTGRES_INITDB_ARGS: "--auth-host=md5"

  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 10Gi
    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS)
    ##
    # storageClass: "-"
    existingClaim: null

  podAnnotations: {}  
  annotations: {}
  strategy: {}

es:
  replicaCount: 1
  image:
    repository: elasticsearch
    tag: 7.5.0
    pullPolicy: IfNotPresent
  env:
    ELASTIC_PASSWORD: elasticsearch
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    discovery.type: single-node 

  # Network configuration
  service:
    type: ClusterIP
    annotations: {}

  persistence:
    enabled: false
    accessMode: ReadWriteOnce
    size: 8Gi
    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS)
    ##
    # storageClass: "-"
    existingClaim: ""

  strategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 0
  #
  # or
  #
  # type: Recreate
  # rollingUpdate: null
  annotations: {}
  podAnnotations: {}