apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ldifs
  labels:
    app.kubernetes.io/name: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  {{- (.Files.Glob "ldifs/*").AsConfig | nindent 2 }}
